# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  create:
    branches: 
      - release/**
  push:
    paths-ignore:
    - 'README.md'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'TeubDev.Moq.AutoMock.HttpClient.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push **\*.nupkg -s 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.GITHUBPUSH}}